// -------------------------------------------------------------
//
// File Name: /Users/rauhul/Documents/MATLAB/codegen/sigmoid/hdlsrc/sigmoid_fixpt.v
// Created: 2016-11-27 09:44:54
//
// Generated by MATLAB 9.1, MATLAB Coder 3.2 and HDL Coder 3.9
//
//
//
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
//
// -------------------------------------------------------------


// -------------------------------------------------------------
//
// Module: sigmoid_fixpt
// Source Path: sigmoid_fixpt
// Hierarchy Level: 0
//
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module sigmoid_fixpt(
                     x_1,
                     result
                    );

    input   signed [31:0] x_1;  // sfix32_En22
    output  [31:0] result;  // ufix32_En31


    reg [31:0] result_1;  // ufix32_En31
    reg sigmoid_fixpt_sign;
    reg signed [31:0] sigmoid_fixpt_tmp;  // sfix32_En22
    reg [31:0] sigmoid_fixpt_pow1;  // ufix32_En23
    reg [31:0] sigmoid_fixpt_approx;  // ufix32_En16
    reg [32:0] sigmoid_fixpt_b1;  // ufix33_En16
    reg [64:0] sigmoid_fixpt_tmp_0;  // ufix65_En24
    reg [32:0] sigmoid_fixpt_b1_0;  // ufix33_En16
    reg [41:0] sigmoid_fixpt_tmp_1;  // ufix42_En24
    reg [55:0] sigmoid_fixpt_div_temp;  // ufix56_En24
    reg [40:0] sigmoid_fixpt_div_temp_0;  // ufix41_En24
    reg [32:0] sigmoid_fixpt_add_cast;  // ufix33_En23
    reg [32:0] sigmoid_fixpt_add_temp;  // ufix33_En23
    reg [40:0] sigmoid_fixpt_add_cast_0;  // ufix41_En23
    reg signed [32:0] sigmoid_fixpt_cast;  // sfix33_En23
    reg signed [64:0] sigmoid_fixpt_mul_temp;  // sfix65_En45
    reg signed [63:0] sigmoid_fixpt_cast_0;  // sfix64_En45
    reg signed [64:0] sigmoid_fixpt_cast_1;  // sfix65_En46
    reg signed [64:0] sigmoid_fixpt_cast_2;  // sfix65_En46
    reg [31:0] sigmoid_fixpt_add_cast_1;  // ufix32_En15
    reg [40:0] sigmoid_fixpt_add_cast_2;  // ufix41_En23
    reg [40:0] sigmoid_fixpt_add_temp_0;  // ufix41_En23
    reg [32:0] sigmoid_fixpt_add_cast_3;  // ufix33_En16
    reg [32:0] sigmoid_fixpt_add_cast_4;  // ufix33_En16
    reg [55:0] sigmoid_fixpt_cast_3;  // ufix56_En40


    always @(x_1) begin
        //HDL code generation from MATLAB function: sigmoid_fixpt
        //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        //                                                                          %
        //           Generated by MATLAB 9.1 and Fixed-Point Designer 5.3           %
        //                                                                          %
        //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        //This function computes the sigmoid of an input x
        sigmoid_fixpt_sign = x_1 > 32'sb00000000000000000000000000000000;
        if ( ! sigmoid_fixpt_sign) begin
            sigmoid_fixpt_tmp =  - (x_1);
        end else begin
            sigmoid_fixpt_tmp = x_1;
        end

        sigmoid_fixpt_pow1 = {sigmoid_fixpt_tmp[30:0], 1'b0};
        sigmoid_fixpt_add_cast = {1'b0, sigmoid_fixpt_pow1};
        sigmoid_fixpt_add_temp = 33'h000800000 + sigmoid_fixpt_add_cast;
        sigmoid_fixpt_add_cast_0 = {8'b0, sigmoid_fixpt_add_temp};
        sigmoid_fixpt_cast = {1'b0, sigmoid_fixpt_pow1};
        sigmoid_fixpt_mul_temp = sigmoid_fixpt_cast * sigmoid_fixpt_tmp;
        sigmoid_fixpt_cast_0 = sigmoid_fixpt_mul_temp[63:0];
        sigmoid_fixpt_cast_1 = {sigmoid_fixpt_cast_0, 1'b0};
        sigmoid_fixpt_cast_2 = sigmoid_fixpt_cast_1 >>> 8'd1;
        sigmoid_fixpt_add_cast_1 = sigmoid_fixpt_cast_2[62:31];
        sigmoid_fixpt_add_cast_2 = {1'b0, {sigmoid_fixpt_add_cast_1, 8'b00000000}};
        sigmoid_fixpt_add_temp_0 = sigmoid_fixpt_add_cast_0 + sigmoid_fixpt_add_cast_2;
        sigmoid_fixpt_approx = sigmoid_fixpt_add_temp_0[38:7];
        sigmoid_fixpt_add_cast_3 = {1'b0, sigmoid_fixpt_approx};
        sigmoid_fixpt_b1 = 33'h000010000 + sigmoid_fixpt_add_cast_3;
        sigmoid_fixpt_tmp_0 = 65'h1FFFFFFFFFFFFFFFF;
        sigmoid_fixpt_add_cast_4 = {1'b0, sigmoid_fixpt_approx};
        sigmoid_fixpt_b1_0 = 33'h000010000 + sigmoid_fixpt_add_cast_4;

        if (sigmoid_fixpt_sign) begin
            if (sigmoid_fixpt_b1 == 33'h000000000) begin
            end else begin
                sigmoid_fixpt_cast_3 = {sigmoid_fixpt_approx, 24'b000000000000000000000000};
                if (sigmoid_fixpt_b1 == 31'sd0) begin
                    sigmoid_fixpt_div_temp = 56'hFFFFFFFFFFFFFF;
                end else begin
                    sigmoid_fixpt_div_temp = sigmoid_fixpt_cast_3 / sigmoid_fixpt_b1;
                end
                sigmoid_fixpt_tmp_0 = {9'b0, sigmoid_fixpt_div_temp};
            end
        end else begin
            sigmoid_fixpt_tmp_0 = 65'h00000000000000000;
        end

        if (sigmoid_fixpt_sign) begin
            sigmoid_fixpt_tmp_1 = 42'h00000000000;
        end else if (sigmoid_fixpt_b1_0 == 33'h000000000) begin
            sigmoid_fixpt_tmp_1 = 42'h3FFFFFFFFFF;
        end else begin
            if (sigmoid_fixpt_b1_0 == 31'sd0) begin
                sigmoid_fixpt_div_temp_0 = 41'h1FFFFFFFFFF;
            end else begin
                sigmoid_fixpt_div_temp_0 = 41'h10000000000 / sigmoid_fixpt_b1_0;
            end
            sigmoid_fixpt_tmp_1 = {1'b0, sigmoid_fixpt_div_temp_0};
        end

        if (sigmoid_fixpt_sign) begin
            result_1 = {sigmoid_fixpt_tmp_0[24:0], 7'b0000000};
        end else begin
            result_1 = {sigmoid_fixpt_tmp_1[24:0], 7'b0000000};
        end
    end

    assign result = result_1;

endmodule  // sigmoid_fixpt